name = "agente-agricola-fresas"
main = "src/index.js"
compatibility_date = "2025-06-29"

[vars]
SUPABASE_URL = "https://iskxnyxbqrjebyxkmzig.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlza3hueXhicXJqZWJ5eGttemlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDM4NTEsImV4cCI6MjA2Njc3OTg1MX0.RBi6lok70-tSPC30Akq-x_Nc0A4s_Xssx3VgHLx-P3w"
# INFLUXDB_URL y INFLUXDB_TOKEN se configurarán más adelante
# OPENAI_API_KEY se debe configurar como secreto

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-kv-namespace-preview-id"